output_path = "data/outputs"
video_path = "/home/victor/projects/automatic_instance_seg/data/inputs/[UCCUSS] Akiba Meido Sensou アキバ冥途戦争 第06話 「姉妹盃に注ぐ血 赤バットの凶行」 NCED Ver. (BD 1920x1080p AVC FLAC).mkv"
screenshots_folder = "screenshots"
uniques_folder = "uniques"
folder_path = ""
similarity_threshold = 0.95


[detector]
config_file = "Detector/yolox/yolox_s_8x8_300e_maids.py"
checkpoint_file = "Detector/yolox/epoch_64.pth"
conf_threshold = 0.80
classes = ['nagomi', 'ranko', 'yumechi', 'shiipon']

[annotations]
revise_annotations = true
show_annotations = true
revised = true
annotations_file = "/home/victor/projects/automatic_instance_seg/data/outputs/[UCCUSS] Akiba Meido Sensou アキバ冥途戦争 第06話 「姉妹盃に注ぐ血 赤バットの凶行」 NCED Ver. (BD 1920x1080p AVC FLAC)/chapter6/annotations/instances_default_updated.json"
images_directory = "/home/victor/projects/automatic_instance_seg/data/outputs/[UCCUSS] Akiba Meido Sensou アキバ冥途戦争 第06話 「姉妹盃に注ぐ血 赤バットの凶行」 NCED Ver. (BD 1920x1080p AVC FLAC)/chapter6/images"