output_path = "data/outputs"
video_path = "YOUR-VIDEO-PATH"
screenshots_folder = "screenshots"
uniques_folder = "uniques"
folder_path = ""
similarity_threshold = 0.95


[detector]
config_file = "YOUR-DETECTOR-CONFIGURATION-FILE"
checkpoint_file = "YOUR-DETECTOR-CHECKPOINT-FILE"
conf_threshold = 0.80
classes = ['A LIST OF YOUR DETECTOR CLASSES']

[annotations]
revise_annotations = true
show_annotations = true
revised = true
annotations_file = ""
images_directory = ""
save_plots = true